const destination=document.getElementById("destination"),messages=document.getElementById("messages");
const routes={school:["School Gate Stop","24","4 min"],"city centre":["Al Azbakeyia Station","24","3 min"],"home":["Al Azbakeyia Station","17","8 min"],"hospital":["Opera Stop","41","14 min"]};
function add(text,cls){const d=document.createElement("div");d.className="msg "+cls;d.textContent=text;messages.appendChild(d);messages.scrollTop=messages.scrollHeight}
function answer(q){let x=q.toLowerCase();let key=Object.keys(routes).find(k=>x.includes(k));if(x.includes("nearest")||x.includes("closest"))return "Your nearest example stop is Al Azbakeyia Station, about 0.4 km away — roughly a 5 minute walk.";if(key){let r=routes[key];return `For ${key}, I recommend bus ${r[1]}. Board at ${r[0]}; the example arrival is in about ${r[2]}.`;}if(x.includes("bus"))return "Tell me your destination, like “City Centre” or “School”, and I’ll suggest an example route.";return "Try asking “nearest stop”, “next bus”, or tell me your destination."}
function send(){let q=document.getElementById("chatInput").value.trim();if(!q)return;add(q,"usermsg");document.getElementById("chatInput").value="";setTimeout(()=>add(answer(q),"botmsg"),350)}
document.getElementById("send").onclick=send;document.getElementById("chatInput").addEventListener("keydown",e=>{if(e.key==="Enter")send()});
document.querySelectorAll(".chat-suggestions button").forEach(b=>b.onclick=()=>{document.getElementById("chatInput").value=b.textContent==="Nearest stop"?"nearest stop":b.textContent==="Next bus"?"next bus":b.textContent;send()});
document.querySelectorAll(".quick button").forEach(b=>b.onclick=()=>{destination.value=b.dataset.dest;document.getElementById("findBtn").click()});
document.getElementById("findBtn").onclick=()=>{let q=destination.value||"City Centre";add("Find bus to "+q,"usermsg");setTimeout(()=>add(answer(q),"botmsg"),250);document.getElementById("chat").scrollIntoView({behavior:"smooth",block:"center"})};
document.getElementById("locBtn").onclick=()=>{if(!navigator.geolocation){alert("Location is not supported by this browser.");return}navigator.geolocation.getCurrentPosition(()=>{document.getElementById("locBtn").textContent="✓ Location enabled";document.getElementById("nearest").textContent="Nearest stop found near you";},()=>alert("Location permission was not granted. You can still use the example stops and routes."))};
document.getElementById("refresh").onclick=()=>{const b=document.getElementById("busBoard");b.style.opacity=".45";setTimeout(()=>b.style.opacity="1",300)};